Feature/get or else
grandcentrix/grandcentrix-kotlin-either pull request #19
Opened 2021-02-23 13:08 UTC by riedhammer

#### Description:
Adds more helper functions:
-> isFailure
-> isSuccess
-> getOrElse
 
#### How to test:

#### Merge information:

2021-02-23 15:19 UTC, lukasz-kalnik-gcx commented on either/src/main/kotlin/net/grandcentrix/either/Either.kt
> +    return fold(succeeded = { it }, failed = onFailure)
This function could have an expression body as it consists of only one expression.
Also this is currently positioned between all the deprecated functions. It could be beneficial to position it directly under the first extension function, `flatMap` (i.e. in line 124).

2021-02-23 15:19 UTC, lukasz-kalnik-gcx commented on either/src/test/kotlin/net/grandcentrix/either/EitherTest.kt
> +    fun `when isSuccess on success return false`() {
Should be `true`.

2021-02-23 15:19 UTC, lukasz-kalnik-gcx commented on either/src/test/kotlin/net/grandcentrix/either/EitherTest.kt
> +    fun `when isSuccess on failure return false`() {
BTW the names are all the other way around. Should be:
```
when failure then isSuccess returns false
```
or
```
on failure isSuccess returns false
```
but not both `when` and `on`...

2021-02-23 15:19 UTC, lukasz-kalnik-gcx commented on either/src/test/kotlin/net/grandcentrix/either/EitherTest.kt
> +    fun `when getOrElse with no failure should return success`() {
This naming convention is based on the given / when / then schema:
given (some initial condition)
when (we do something)
then (we get some result)

So proper grammar is here:
```
when success then getOrElse should return success
```
Why "no failure"? No failure is a success :)

2021-02-23 16:16 UTC, lukasz-kalnik-gcx commented
I have moved all the deprecated functions to a separate file so now it will be easier to add new functions.

2021-02-24 10:34 UTC, riedhammer commented on either/src/main/kotlin/net/grandcentrix/either/Either.kt
> +    val isSuccess: Boolean get() = this is Success
In my view it is simpler to use and we could have this check only at one place.
Mostly i want to check a result in a test like:

`assertTrue(result.isSuccess)`

here you can use the auto complete from the ide.

2021-02-24 15:47 UTC, lukasz-kalnik-gcx requested changes

2021-02-24 15:47 UTC, lukasz-kalnik-gcx commented on either/src/test/kotlin/net/grandcentrix/either/EitherTest.kt
> +    fun `when success then getOrElse returns else block`() {
Should be `failure`

2021-02-24 15:47 UTC, lukasz-kalnik-gcx commented on README.md
> +getOrElse {} // returns the encapsulated value if success or the result of the given code block
Please also add the `isSuccess` and `isFailure` convenience properties to the API description.

2021-02-24 15:47 UTC, lukasz-kalnik-gcx commented on either/src/main/kotlin/net/grandcentrix/either/Either.kt
> +     * In this case [isFailure] returns `false`.
There is no point to describe in the documentation to `isSuccess` what `isFailure` does.
Better would be to write something like:
```
Returns `true` if this instance represents a successful outcome, `false` otherwise.
```

2021-02-24 15:47 UTC, lukasz-kalnik-gcx commented on either/src/main/kotlin/net/grandcentrix/either/Either.kt
> +     * In this case [isSuccess] returns `false`.
See the comment to `isSuccess` 👆

2021-02-24 15:47 UTC, lukasz-kalnik-gcx commented on either/src/main/kotlin/net/grandcentrix/either/Either.kt
> + * This function is a shorthand for `fold(onSuccess = { it }, onFailure = onFailure)` (see [fold]).
The first parameter name for `fold` is actually called `succeeded` (you can see it in the function implementation).

2021-02-25 12:59 UTC, lukasz-kalnik-gcx approved these changes
Looks good now. Thank you for your contribution!

2021-02-25 13:01 UTC, merged